[package]
name = "ego-cli"
version = "0.1.0"
authors = ["Michael Neumann <mneumann@ntecs.de>"]
license = "MIT"
repository = "https://github.com/mneumann/ego"

[dependencies]
ego = { path = "..", version = "0.0.1" }
serde_json = "1.0"
rand = "0.4"
